version: '3.9'

services:
  db:
    image: postgres:16.4
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    image: your-ecr-repository-url # This will be updated dynamically by the GitHub Actions workflow
    container_name: django_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB_HOST=${POSTGRES_DB}
      - POSTGRES_NAME=${POSTGRES_USER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
