name: CI/CD Pipeline

on:
  push:
    branches:
      - master

  tag:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli -y

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Extract repository name from Git URL
      run: |
        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

    - name: Create ECR Repository if not exists
      run: |
        aws ecr describe-repositories --repository-names "$REPO_NAME" || aws ecr create-repository --repository-name "$REPO_NAME"
      env:
        REPO_NAME: ${{ env.REPO_NAME }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Authenticate Docker to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}
      env:
        REPO_NAME: ${{ env.REPO_NAME }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: Build and push Docker image with 'latest' tag
      id: build-image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}
        docker build -t $IMAGE_URI:latest .
        docker push $IMAGE_URI:latest
      env:
        REPO_NAME: ${{ env.REPO_NAME }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Deploy to EC2
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}
        ssh -o StrictHostKeyChecking=no -i "ec2_key.pem" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          docker pull $IMAGE_URI:latest
          docker stop new_app_container || true
          docker rm new_app_container || true
          docker run -d -p 8001:8001 --name new_app_container $IMAGE_URI:latest
        EOF

      env:
        REPO_NAME: ${{ env.REPO_NAME }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
