name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli -y

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-north-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: private

    - name: Build and push Docker image
      id: build-image
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        IMAGE_URI=022499008567.dkr.ecr.eu-north-1.amazonaws.com/deploy_test
        docker build -t $IMAGE_URI:${IMAGE_TAG} .
        docker push $IMAGE_URI:${IMAGE_TAG}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem

    - name: Deploy to EC2
      run: |
        IMAGE_TAG=${GITHUB_SHA}
        IMAGE_URI=022499008567.dkr.ecr.eu-north-1.amazonaws.com/deploy_test
        ssh -o StrictHostKeyChecking=no -i "ec2_key.pem" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          docker pull $IMAGE_URI:${IMAGE_TAG}
          docker stop my-app || true
          docker rm my-app || true
          docker run -d -p 8000:8000 --name my-app $IMAGE_URI:${IMAGE_TAG}
        EOF

      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: eu-north-1
        IMAGE_TAG: ${{ github.sha }}
