name: CICD Testing EC2

on:
  push:
    branches:
      - prod


jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test_server_django:latest .

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test_server_django:latest


  deploy:
    needs: build

    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/test_server_django:latest

      - name: Remove old container
        run: docker rm -f test_server_django

      - name: Run docker container
        run: docker run -d -p 8000:8000 --name test_server_django ${{ secrets.DOCKER_USERNAME }}/test_server_django:latest

